<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Strings for component 'paygw_stripe', language 'en'
 *
 * @package    paygw_stripe
 * @copyright  Alex Morris <alex@navra.nz>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['allowpromotioncodes'] = 'Allow Promotion Codes';
$string['alreadydeliveredcourse'] = 'This course is already delivered to you, if you believe there has been an error contact your site administrator.';
$string['anchoredbilling'] = 'Use the start of the subscription interval as a fixed billing date.';
$string['anchoredbilling_help'] =
    'E.g. For a monthly subscription, billing will be done every 1st of the month. If a user subscribes in the middle of the month, they will be charged a prorated amount covering from the registration day to the end of the month';
$string['apikey'] = 'Publishable Key';
$string['apikey_help'] = 'The API key that we use to identifier ourselves with Stripe';
$string['apiwebhookerror'] = 'There was an error while creating a webhook using the given API keys.';
$string['cancel'] = 'Cancel';
$string['cancelsubscription'] = 'Cancel subscription';
$string['cancelsubscriptionconfirm'] = 'Are you sure you wish to cancel this subscription?';
$string['cancelsubscriptions'] = 'Change Subscriptions';
$string['collectbillingaddress'] = 'Collect billing address';
$string['collectbillingaddress_desc'] = 'Require billing address in checkout';
$string['customerdescription'] = 'Moodle User ID: {$a}';
$string['customsubscriptioninterval'] = 'Custom Subscription Period';
$string['customsubscriptioninterval:day'] = 'Day';
$string['customsubscriptioninterval:month'] = 'Month';
$string['customsubscriptioninterval:week'] = 'Week';
$string['customsubscriptioninterval:year'] = 'Year';
$string['customsubscriptionintervalcount'] = 'Custom Subscription Period Interval';
$string['customsubscriptionintervalcount_help'] = '';
$string['defaulttaxbehavior'] = 'Default tax behavior';
$string['defaulttaxbehavior_help'] = 'Default behavior of tax (inclusive, exclusive). Changeable in Stripe dashboard.';
$string['enableautomatictax'] = 'Enable automatic tax';
$string['enableautomatictax_desc'] = 'Automatic tax must be enabled and configured in the Stripe dashboard.';
$string['failedtosetdefaultpaymentmethod'] = 'Failed to set up a payment method for subscription, please try again.';
$string['fee'] = 'Fee';
$string['forcedlocale'] = 'Force locale';
$string['forcedlocale_desc'] = 'Force locale for checkout, invoices, any Stripe related pages. If empty we will attempt to use the users locale pulled from the Moodle language settings.';
$string['gatewaydescription'] = 'Stripe is an authorised payment gateway provider for processing credit card transactions.';
$string['gatewayname'] = 'Stripe';
$string['invalidsessionbinding'] = 'This payment session does not match the requested item.';
$string['invoicecreation'] = 'Automatic Invoices';
$string['invoicecreation_desc'] = 'Generate post-purchase invoice for one-time payments';
$string['invalidinvoicebinding'] = 'The Stripe invoice does not match the original purchase. Please contact the site administrator.';
$string['invalidinvoicecontinuation'] = 'This billing-details link is invalid, expired or cancelled. Please restart your purchase.';
$string['invoicebillingcancelled'] = 'You returned from the billing-details step. No new invoice was created by this return.';
$string['invoicepaymentmethodsfailed'] = 'The invoice payment options could not be prepared. Please reload this page to retry the same invoice. No invoice email has been requested yet. If the problem persists, contact the site administrator.';
$string['privacy:metadata:stripe_invoices:paymentmethodstatus'] = 'Status of preparing invoice payment options';
$string['privacy:metadata:stripe_invoices:paymentmethods'] = 'Stripe payment methods saved for this invoice';
$string['invoicebankcountry'] = 'Bank country for EUR invoices';
$string['invoicebankcountry_help'] = 'New EUR invoice purchases retain the payment methods Stripe resolves from the invoice settings and additionally offer EU bank transfer. Choose the country of the bank details generated by Stripe: Germany, France, Ireland or the Netherlands. The default is Germany (DE). This is not the customer billing country. The choice is saved when the purchase starts. Other currencies continue to use the Stripe invoice payment settings.';
$string['invalidinvoicebankcountry'] = 'Select a supported EUR bank country: DE, FR, IE or NL.';
$string['privacy:metadata:stripe_invoices:banktransfercountry'] = 'Bank country selected for the EUR invoice purchase';
$string['invoicebillingincomplete'] = 'Please save your billing name, email and address in Stripe before continuing.';
$string['invoicebusy'] = 'This invoice is being processed. Please try again shortly.';
$string['invoicedeliveryfailed'] = 'The paid order could not be delivered. Stripe will retry the notification.';
$string['invoiceemailfailed'] = 'The invoice was finalized, but its email request could not be confirmed. Please reload this page to retry the same invoice. If the problem persists, contact the site administrator.';
$string['invoiceemailrecoveryrequired'] = 'The invoice email status needs review. Please ask the site administrator to check the invoice in Stripe before sending it again.';
$string['invoicerecoveryrequired'] = 'This invoice attempt needs review. Please ask the site administrator to check Stripe before retrying the purchase.';
$string['invoiceunavailable'] = 'This invoice is unavailable. Please contact the site administrator or restart your purchase if it was voided.';

$string['messageprovider:payment_failed'] = 'Failed delayed payment notification';
$string['messageprovider:payment_successful'] = 'Successful delayed payment confirmation notification';

$string['payment:failed:message'] = 'Your payment failed to clear, please check your payment details and try again.';
$string['payment:failed:subject'] = 'Payment failed';
$string['payment:successful:message'] = 'Your payment was successful, you can now visit {$a->url}';
$string['payment:successful:subject'] = 'Payment successful';

$string['paymentcancelled'] = 'Payment was cancelled';

$string['paymenterror'] = 'There was an error processing your payment, please contact the site administrator for help';

$string['paymentmethod:alipay'] = 'Alipay';
$string['paymentmethod:bancontact'] = 'Bancontact';
$string['paymentmethod:card'] = 'Card';
$string['paymentmethod:eps'] = 'EPS';
$string['paymentmethod:giropay'] = 'giropay';
$string['paymentmethod:ideal'] = 'iDEAL';
$string['paymentmethod:klarna'] = 'Klarna';
$string['paymentmethod:nz_bank_account'] = 'NZ BECS Direct Debit';
$string['paymentmethod:p24'] = 'P24';
$string['paymentmethod:paypal'] = 'PayPal';
$string['paymentmethod:sepa_debit'] = 'SEPA Direct Debit';
$string['paymentmethod:twint'] = 'TWINT';
$string['paymentmethod:wechat_pay'] = 'WeChat Pay';

$string['paymentmethodconfiguration'] = 'Payment Method Configuration';
$string['paymentmethodconfiguration_help'] = 'Select a Stripe Payment Method configuration to use for this gateway. Update your payment methods in the Stripe dashboard.';
$string['paymentmethodconfigurationlink'] = 'Manage your payment methods on the <a href="https://dashboard.stripe.com/settings/payment_methods">Stripe dashboard settings page</a>.';
$string['paymentmethodconfigurationsavekeysfirst'] = 'Save your Stripe API keys first, then select a payment method configuration.';
$string['paymentmethods'] = 'Payment Methods';
$string['paymentpending'] = 'Payment is pending, you will be enrolled when the payment has cleared.';
$string['paymentsuccessful'] = 'Payment was successful';
$string['paymenttype'] = 'Payment Type';
$string['paymenttype:onetime'] = 'One Time';
$string['paymenttype:subscription'] = 'Subscription';
$string['paymenttype:invoice'] = 'Invoice payment';
$string['paymenttype_help'] = 'Invoice payment collects billing details in Stripe first, then emails and opens a standalone invoice due in 14 days. Stripe sends the email to the billing email address. Course access is granted only when Stripe reports the invoice paid. Checkout promotion codes and Checkout payment-method configuration do not apply to invoices.';
$string['privacy:metadata:stripe_invoices'] = 'Stores pending billing flows and their Stripe invoice, purchase and payment references. Billing identity and tax information remain in Stripe.';
$string['privacy:metadata:stripe_invoices:userid'] = 'Moodle user ID';
$string['privacy:metadata:stripe_invoices:customerid'] = 'Stripe customer ID';
$string['privacy:metadata:stripe_invoices:invoiceid'] = 'Stripe invoice ID';
$string['privacy:metadata:stripe_invoices:amounttotal'] = 'Invoice total in the smallest currency unit';
$string['privacy:metadata:stripe_invoices:status'] = 'Billing flow or invoice status';
$string['privacy:metadata:stripe_invoices:delivered'] = 'Whether the purchase has been delivered';
$string['privacy:metadata:stripe_invoices:emailstatus'] = 'Status of the invoice email request to Stripe';
$string['privacy:metadata:stripe_invoices:timeemailstarted'] = 'Time of the first invoice email attempt';
$string['privacy:metadata:stripe_invoices:timeemailsent'] = 'Time Stripe accepted the invoice email request';
$string['privacy:metadata:stripe_customers:billingmanaged'] = 'Whether billing identity is maintained in Stripe instead of the Moodle profile';
$string['pluginname'] = 'Stripe';
$string['pluginname_desc'] = 'The Stripe plugin allows you to receive payments via Stripe.';

$string['privacy:metadata:stripe_checkout_sessions'] = 'Stores payment checkout data to track payment history';
$string['privacy:metadata:stripe_checkout_sessions:userid'] = 'Moodle user ID';
$string['privacy:metadata:stripe_customers'] = 'Stores the relation from Moodle users to Stripe customer objects';
$string['privacy:metadata:stripe_customers:customerid'] = 'Customer ID returned from Stripe';
$string['privacy:metadata:stripe_customers:userid'] = 'Moodle user ID';
$string['privacy:metadata:stripe_subscriptions'] =
    'Stores the relation from subscriptions in Moodle to Stripe subscription objects';
$string['privacy:metadata:stripe_subscriptions:userid'] = 'Moodle user ID';

$string['product'] = 'Product';
$string['profilecat'] = 'Stripe Payment Subscriptions';
$string['scheduledrenewal'] = 'Scheduled Renewal';
$string['secretkey'] = 'Secret Key';
$string['secretkey_help'] = 'Secret key to authenticate with Stripe';
$string['status'] = 'Status';
$string['stripeaccount'] = 'Stripe account ID';
$string['stripeaccount_help'] = 'For creating the direct charge branding page';
$string['subscriptionerror'] = 'There was an error creating the subscription, please contact the site administrator for help';
$string['subscriptioninterval'] = 'Subscription Period';
$string['subscriptioninvalid'] = 'Invalid subscription, please contact the site administrator for help';

$string['subscriptionperiod:custom'] = 'Custom';
$string['subscriptionperiod:daily'] = 'Daily';
$string['subscriptionperiod:every3months'] = 'Every 3 Months';
$string['subscriptionperiod:every6months'] = 'Every 6 Months';
$string['subscriptionperiod:monthly'] = 'Monthly';
$string['subscriptionperiod:weekly'] = 'Weekly';
$string['subscriptionperiod:yearly'] = 'Yearly';

$string['subscriptions'] = 'Subscriptions';
$string['subscriptionssubheading'] =
    'This page lists the subscriptions you have purchased. You can cancel subscriptions here, cancellations will be processed immediately and you will not be able to enter the course again.';

$string['subscriptionstatus:active'] = 'Active';
$string['subscriptionstatus:canceled'] = 'Cancelled';
$string['subscriptionstatus:incomplete'] = 'Incomplete';
$string['subscriptionstatus:incomplete_expired'] = 'Expired';
$string['subscriptionstatus:past_due'] = 'Payment Past Due';
$string['subscriptionstatus:paused'] = 'Paused';
$string['subscriptionstatus:trialing'] = 'Trialing';
$string['subscriptionstatus:unpaid'] = 'Unpaid';

$string['subscriptionsuccessful'] = 'Successfully subscribed. You can manage your Stripe Payment subscriptions from your profile page.';

$string['taxbehavior:exclusive'] = 'Exclusive';
$string['taxbehavior:inclusive'] = 'Inclusive';

$string['trialperiod'] = 'Trial Period';
$string['trialperiod_help'] = 'E.g. the first interval is free. If the subscription is created on the 24th April, a month is free and billing starts on the 24th May.<br/>
    If billing happens at the start of the interval (e.g. on the 1st of the month), the pro-rated amount is waved. If a user registers on the 24th April, April is free and billing starts on the 1st May';
$string['updatepaymentmethod'] = 'Update Payment Method';
